apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-micro
  template:
    metadata:
      labels:
        app: bank-micro
    spec:
      containers:
        - name: bank-micro
          image: bank-micro:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://192.168.49.2:3306/alinedb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: bank-ms-nodeport
spec:
  type: NodePort
  selector:
    app: bank-micro
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083