# portal-dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-portal
  template:
    metadata:
      labels:
        app: member-portal
    spec:
      containers:
      - name: member-portal
        image: member-nginx:v2
        ports:
        - containerPort: 4200
        env:
        - name: api
          value: http://aline-gateway:8080/api
        - name: landingPortal
          value: http://landing-portal:3007

---
# portal-dashboard-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: member-nodeport
spec:
  selector:
    app: member-portal
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80


