apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-micro
  template:
    metadata:
      labels:
        app: transaction-micro
    spec:
      containers:
        - name: transaction-micro
          image: transaction-micro:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://192.168.49.2:3306/alinedb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8073
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-ms-nodeport
spec:
  type: NodePort
  selector:
    app: transaction-micro
  ports:
    - protocol: TCP
      port: 8073
      targetPort: 8073
      nodePort: 30073