apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriter-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriter-micro
  template:
    metadata:
      labels:
        app: underwriter-micro
    spec:
      containers:
        - name: underwriter-micro
          image: underwriter-micro:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://192.168.49.2:3306/alinedb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: under-ms-nodeport
spec:
  type: NodePort
  selector:
    app: underwriter-micro
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30071