apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-micro
  template:
    metadata:
      labels:
        app: user-micro
    spec:
      containers:
        - name: user-micro
          image: micro-user:v11
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://aline-mysql:3306/alinedb
            - name: DB_USERNAME
              value: root
              # valueFrom:
              #   secretKeyRef:
              #     name: aline-secret
              #     key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: user-ms-nodeport
spec:
  type: NodePort
  selector:
    app: user-micro
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30070