pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh """
                    docker build -t account-micro-jenk .
                """
            }
        }
        stage('Test') {
            steps {

            }
        }
        stage('Deploy') {
            steps {

            }
        }
    }
}