apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-micro
  labels:
    app: account-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-micro
  template:
    metadata:
      labels:
        app: account-micro
        target: microservice
    spec:
      containers:
        - name: account-micro
          image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:account-micro-v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: alinedb.c9aaakygudzw.us-east-1.rds.amazonaws.com
            - name: DB_NAME
              value: alinedb
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8072
---
apiVersion: v1
kind: Service
metadata:
  name: account-ms-nodeport
spec:
  type: ClusterIP
  selector:
    app: account-micro
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072
