# portal-admin-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  labels:
    app: admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
        target: portals
    spec:
      containers:
      - name: admin-portal
        image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:admin-portal-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASEURL
          valueFrom:
            configMapKeyRef:
              name: aline-config
              key: GATEWAY_URL
        - name: REACT_APP_TOKEN_NAME
          value: x2wOrQfY6RQIfE1ETwZtpflC19KyfN9N
        - name: REACT_APP_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_LANDING

# ---
# # portal-admin-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: admin-lb
# spec:
#   type: LoadBalancer
#   selector:
#     app: admin-portal
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 80


