# aline-gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-gateway
  labels: 
    app: aline-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-gateway
  template:
    metadata:
      labels:
        app: aline-gateway
    spec:
      containers:
      - name: aline-gateway
        image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:aline-gateway-jenkins-latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_SERVICE_HOST
          value: gateway-svc.default.svc.cluster.local
        - name: PORTAL_LANDING
          valueForm:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_LANDING
        - name: PORTAL_DASHBOARD
          valueForm:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_DASHBOARD
        - name: PORTAL_ADMIN
          valueForm:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_ADMIN
        - name: JWT_SECRET_KEY
          value: x2wOrQfY6RQIfE1ETwZtpflC19KyfN9N
        - name: ENCRYPT_SECRET_KEY
          value: mf5ZIxRkF6IJj1AIVreII2ZQ4uhtJ8zC

# ---
# # aline-gateway-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: gateway-lb
# spec:
#   type: LoadBalancer
#   selector:
#     app: aline-gateway
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
