# portal-dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-portal
  template:
    metadata:
      labels:
        app: member-portal
    spec:
      containers:
      - name: member-portal
        image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:member-aws-v1
        ports:
        - containerPort: 4200
        env:
        - name: api
          value: http://a2d1caf77098d4f83b7912fe3964db50-1192861274.us-east-1.elb.amazonaws.com:8080/api
        - name: landingPortal
          value: http://a07dff4af00f9458b93c1f384f619955-953394416.us-east-1.elb.amazonaws.com:3007


---
# portal-dashboard-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: member-lb
spec:
  type: LoadBalancer
  selector:
    app: member-portal
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
