# portal-dashboard-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-portal
  template:
    metadata:
      labels:
        app: member-portal
    spec:
      containers:
      - name: member-portal
        image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:member-dashboard-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
        env:
        - name: api
          valueForm:
            configMapKeyRef:
              name: aline-config
              key: API
        - name: landingPortal
          valueForm:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_LANDING


# ---
# # portal-dashboard-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: member-lb
# spec:
#   type: LoadBalancer
#   selector:
#     app: member-portal
#   ports:
#     - protocol: TCP
#       port: 4200
#       targetPort: 80
