apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-micro
  labels:
    app: user-micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-micro
  template:
    metadata:
      labels:
        app: user-micro
        target: microservice
    spec:
      containers:
        - name: user-micro
          image: 767397723308.dkr.ecr.us-east-1.amazonaws.com/aline-financial-jp:user-micro-jenkins-latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: alinedb.c9aaakygudzw.us-east-1.rds.amazonaws.com
            - name: DB_NAME
              value: alinedb
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aline-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 8070
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-ms-nodeport
# spec:
#   type: ClusterIP
#   selector:
#     app: user-micro
#   ports:
#     - protocol: TCP
#       port: 8070
#       targetPort: 8070
