# aline-gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aline-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aline-gateway
  template:
    metadata:
      labels:
        app: aline-gateway
    spec:
      containers:
      - name: aline-gateway
        image: aline-gateway:v5
        ports:
        - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_SERVICE_HOST
          value: host.docker.internal
        - name: PORTAL_LANDING
          value: http://localhost:3000
        - name: PORTAL_DASHBOARD
          value: http://localhost:4200
        - name: PORTAL_ADMIN
          value: http://localhost:3007
        - name: JWT_SECRET_KEY
          value: x2wOrQfY6RQIfE1ETwZtpflC19KyfN9N
        - name: ENCRYPT_SECRET_KEY
          value: mf5ZIxRkF6IJj1AIVreII2ZQ4uhtJ8zC

---
# aline-gateway-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-nodeport
spec:
  selector:
    app: aline-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: account-micro
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: account-micro
#   template:
#     metadata:
#       labels:
#         app: account-micro
#     spec:
#       containers:
#         - name: account-micro
#           image: account-micro:v1
#           imagePullPolicy: IfNotPresent
#           env:
#             - name: DB_URL
#               value: jdbc:mysql://192.168.49.2:3306/alinedb
#             - name: DB_USERNAME
#               value: root
#             - name: DB_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: aline-secret
#                   key: MYSQL_ROOT_PASSWORD
#           ports:
#             - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: account-ms-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: account-micro
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
#       nodePort: 30080