# portal-landing-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-portal
  labels:
    app: landing-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-portal
  template:
    metadata:
      labels:
        app: landing-portal
        target: portals
    spec:
      containers:
      - name: landing-portal
        image: joehost.jfrog.io/docker-local-docker-local/landing-portal:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3007
        env:
        - name: REACT_APP_API
          valueFrom:
            configMapKeyRef:
              name: aline-config
              key: GATEWAY_URL
        - name: REACT_APP_MEMBER_DASHBOARD_URL
          valueFrom:
            configMapKeyRef:
              name: aline-config
              key: PORTAL_DASHBOARD

---
# portal-landing-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: landing-lb
spec:
  type: LoadBalancer
  selector:
    app: landing-portal
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 80

